[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 132
  multiline_func_header = "all"
  number_underscore = "preserve"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true